
###
# Query Composite API: Load Cases By AccountId
GET http://localhost:8080/v1/composite/0018L00000KhVBPQA3/cases

###
# Query Composite API: Create Case TRACKING_PROBLEM
POST http://localhost:8080/v1/composite
Content-Type: application/json

{
    "salesforceReason": "TRACKING_PROBLEM",
    "customerId": "74674326230",
    "productId": "0987654321",
    "protocolNumber": "123456789",
    "orderId": "REF#000000000"
}

###
# Query Composite API: Create Case TRACKING_PROBLEM
POST http://localhost:8080/v1/composite
Content-Type: application/json

{
    "salesforceReason": "CHANGE_ADDRESS",
    "customerId": "74674326230",
    "productId": "0987654321",
    "protocolNumber": "3425643534",
    "modifyBillingAddress": "false",
    "instalationAddress": {
        "streetAddress": "Av. Paulista",
        "locality": "Centro", 
        "region": "SP",
        "country": "BR",
        "postalCode": "12345-678"
    },
    "technicianVisitOpt1": {
        "dateOption": "2023-03-04",
        "period": "MORNING"
    },
    "technicianVisitOpt2": {
        "dateOption": "2023-03-07",
        "period": "EVENING"
    }
}